name: dartup_meet_with_angular
description: AngularDart application for "Meet with Dart" on DartUP
version: 1.0.0
author: Dmitry Podkorytov <d.podkorytov@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  redux: ^3.0.0

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
